### ISSUE TITLE
Contao 3.5.14

### ISSUE THREAD

**Issue by arraysegment** [menatwork/MultiColumnWizard#206]
Hello,

I'm using Contao 3.5.14.

I'm getting the following error (error.log) when clicking the following:
1. Isotope > Store configuration > USD
2. Isotope > Product types

```
[06-Jul-2016 03:41:25 CET] PHP Fatal error: Uncaught exception 'Error' with message 'Function name must be a string' thrown in /contao/web/system/modules/multicolumnwizard/MultiColumnWizard.php on line 866
#0 /contao/web/system/modules/multicolumnwizard/MultiColumnWizard.php(479): MultiColumnWizard->initializeWidget(Array, 0, 'name', 'type')
#1 /contao/web/system/modules/core/library/Contao/Widget.php(684): MultiColumnWizard->generate()
#2 /contao/web/system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#3 /contao/web/system/modules/core/library/Contao/BaseTemplate.php(88): include('/srv/users/serv...')
#4 /contao/web/system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#5 /contao/web/system/modules/core/classes/DataContainer.php(546): Contao\Widget->parse()
#6 /contao/web/system/modules/core/drivers/DC_Table.php(1951): Contao\DataContainer->row('{name_legend},n...')
#7 /contao/web/system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php(223): Contao\DC_Table->edit()
#8 /contao/web/system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php(69): Isotope\BackendModule\BackendOverview->getModule('producttypes')
#9 /contao/web/system/modules/core/classes/Backend.php(423): Isotope\BackendModule\BackendOverview->generate()
#10 /contao/web/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_setup')
#11 /contao/web/contao/main.php(20): Contao\BackendMain->run()
#12 {main}
```

**Comment by arraysegment** [comment]
Updated MultiColumnWizard 3.3.5
