### ISSUE TITLE
PHP Fehlermeldung bei Date-Feld

### ISSUE THREAD

**Issue by garyee** [menatwork/MultiColumnWizard#210]
Hallo,

Ich verwende den MCW mit dem MooTools Datepicker im FE. Mein "dateFormat" aus der Config ist auf "d.m.Y" gestellt, wenn ich das Datum jetzt aber in einem anderen Format ins Input-Feld schreibe kommt folgender PHP Fehler:

``` php
Fatal error: Uncaught exception OutOfBoundsException with message Invalid date "2000-06-08" thrown in system/modules/core/library/Contao/Date.php on line 434
#0 system/modules/core/library/Contao/Date.php(67): Contao\Date->dateToUnix()
#1 composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php(810): Contao\Date->__construct('2000-06-08', 'd.m.Y')
#2 composer/vendor/menatwork/contao-multicolumnwizard/system/modules/multicolumnwizard/MultiColumnWizard.php(197): MultiColumnWizard->initializeWidget(Array, 0, 'birthday', '2000-06-08')
#3 system/modules/core/library/Contao/Widget.php(798): MultiColumnWizard->validator(Array)
#4 system/modules/hot_tournament/modules/ModuleTeamsRegister.php(358): Contao\Widget->validate()
```

Ich werde mal einen PR dazu erstellen und den hier verlinken. Wenn man an zwei Stellen den Code etwas verändert, zeigt der Datepicker dann nämlich auch einen Fehler an.

**Comment by garyee** [comment]
Please merge.

**Comment by davidmaack** [comment]
Fixd with https://github.com/menatwork/MultiColumnWizard/pull/211
Thanks for the PR  :)
