### ISSUE TITLE
pageTree mit Fehler bei Auswahl einer Seite (Uncaught exception TypeError)

### ISSUE THREAD

**Issue by Dodger77** [menatwork/MultiColumnWizard#217]
Folgenden Fehler erhalte ich, wenn ich eine Seite ausgewählt habe:

```
Fatal error: Uncaught exception TypeError with message Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\ActiveRecord::__construct() must implement interface ContaoCommunityAlliance\DcGeneral\Data\ModelInterface, null given, called in /contao35/htdocs/system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Compatibility/DcCompat.php on line 167 thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Compatibility/ActiveRecord.php on line 42

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/Compatibility/DcCompat.php(167): ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\ActiveRecord->__construct(NULL)
#1 system/modules/multicolumnwizard/MultiColumnWizardHelper.php(149): ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat->__get('activeRecord')
#2 system/modules/core/classes/Ajax.php(468): MultiColumnWizardHelper->executePostActions('reloadPagetree_...', Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#3 system/modules/core/classes/Ajax.php(198): Contao\Ajax->executePostActionsHook(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(239): Contao\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(383): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#7 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(90): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#8 system/modules/core/classes/Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('mm_media', Array)
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_me...')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}
```

MultiColumnWizard 3.3.10 (tritt in 3.3.9) noch nicht auf.

Umgebung:
- Contao 3.5.27
- MetaModels Nightly
- [metamodelsattribute_multi](https://github.com/byteworks-ch/contao-metamodelsattribute_multi/) 1.0.4

**Comment by Dodger77** [comment]
Das hängt wohl mit folgendem Commit zusammen:

https://github.com/menatwork/MultiColumnWizard/commit/80d78a95d2fa26551e3d4e7f8d7388cadfb80ab1

Wenn ich diesen rückgängig mache, tritt auch der Fehler nicht mehr auf.

**Comment by zonky2** [comment]
getestet mit MCW 3.3.12

* Seitenpicker funktioniert aber nur als Einzelauswahl (Radiobuttons)

```
            'mcw_pagetree' => array
                (
                'label'         => &$GLOBALS['TL_LANG'][$strTblName]['mcw_pagetree'],
                'exclude'       => true,
                'inputType'     => 'pageTree',
                'eval'          => array
                    (
                    'fieldType' => 'checkbox',
                    'multiple'  => true
                    )
                ),
```
![shot377](https://user-images.githubusercontent.com/1045318/31357358-ae6e0506-ad41-11e7-9357-155d399e5f93.jpg)
![shot378](https://user-images.githubusercontent.com/1045318/31357365-b2c239a6-ad41-11e7-855b-2c6c09871dc0.jpg)

Duplikat von https://github.com/menatwork/MultiColumnWizard/issues/160
