### ISSUE TITLE
Problem mit Contao 4.11.1 und Parameter "kernel.root_dir"

### ISSUE THREAD

**Issue by hwit-biz** [menatwork/MultiColumnWizard#269]
Guten Abend.

Ich habe soeben eine Neuinstallation von Contao 4.11.1 über den Contao-Manager auf einem neuen VPS vorgenommen und bin über ein Problem gestolpert.

Zum Selbermachen:
1. Contao-Manager im /web Verzeichnis einrichten
2. Contao-Installation starten (bei mir wurde 4.11.1 geladen)
3. Im Contao-Manager zum Beispiel con4gis-Maps oder con4gis-Core installieren
4. Sobald die Installation durch ist kann auf contao/install oder contao/ generell nicht mehr zugegriffen werden > Fehler 500

Hier ein Auszug der /var/log/apache2/error.log:
```
[Wed Mar 10 22:45:03.708967 2021] [negotiation:error] [pid 4443] [client xxx] AH00687: Negotiation: discovered file(s) matching request: /var/www/html/contao/web/contao-manager (None could be negotiated)., referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 22:50:04.279689 2021] [php7:error] [pid 4441] [client xxx] PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException: You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"? in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:98\nStack trace:\n#0 /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(61): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get()\n#1 /var/www/html/contao/vendor/symfony/dependency-injection/Container.php(118): Symfony\\Component\\DependencyInjection\\ParameterBag\\EnvPlaceholderParameterBag->get()\n#2 /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php(66): Symfony\\Component\\DependencyInjection\\Container->getParameter()\n#3 /var/www/html/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): MenAtWork\\ in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 98, referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 22:51:17.014626 2021] [php7:error] [pid 4442] [client xxx] PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException: You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"? in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:98\nStack trace:\n#0 /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(61): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get()\n#1 /var/www/html/contao/vendor/symfony/dependency-injection/Container.php(118): Symfony\\Component\\DependencyInjection\\ParameterBag\\EnvPlaceholderParameterBag->get()\n#2 /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php(66): Symfony\\Component\\DependencyInjection\\Container->getParameter()\n#3 /var/www/html/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): MenAtWork\\ in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 98
[Wed Mar 10 22:53:20.471104 2021] [php7:warn] [pid 4441] [client xxx] PHP Warning:  include(/var/www/html/contao/vendor/codefog/contao-haste/config/upgrade.php): failed to open stream: No such file or directory in /var/www/html/contao/app/Resources/contao/config/runonce.php on line 6, referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 22:53:20.471136 2021] [php7:warn] [pid 4441] [client xxx] PHP Warning:  include(): Failed opening '/var/www/html/contao/vendor/codefog/contao-haste/config/upgrade.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/contao/app/Resources/contao/config/runonce.php on line 6, referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 23:06:33.865505 2021] [php7:error] [pid 4447] [client xxx] PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException: You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"? in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:98\nStack trace:\n#0 /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(61): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get()\n#1 /var/www/html/contao/vendor/symfony/dependency-injection/Container.php(118): Symfony\\Component\\DependencyInjection\\ParameterBag\\EnvPlaceholderParameterBag->get()\n#2 /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php(66): Symfony\\Component\\DependencyInjection\\Container->getParameter()\n#3 /var/www/html/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): MenAtWork\\ in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 98, referer: https://xxx/contao-manager.phar.php/
```

Anscheinend befindet sich in der Datei /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php ein Array mit dem Parameter "kernel.root_dir", welcher wohl in Contao 4.11.1 nicht mehr unterstützt wird. Möglicherweise liegt der Fehler aber auch woanders oder bei meiner Serverkonfiguration...

Sobald das Paket wieder entfernt wird (also con4gis-Maps), verschwindet auch der Fehler 500 wieder.

**Comment by hwit-biz** [comment]
Tut mir leid - hab grade gesehen, dass ich diesen Bug Report wohl besser hier hätte melden sollen:
https://github.com/menatwork/contao-multicolumnwizard-bundle/issues

**Comment by zonky2** [comment]
> Tut mir leid - hab grade gesehen, dass ich diesen Bug Report wohl besser hier hätte melden sollen:
https://github.com/menatwork/contao-multicolumnwizard-bundle/issues

Korrekt! bitte dort machen...
